config/routes.php
<?php
/**
 * Routes configuration
 *
 * In this file, you set up routes to your controllers and their actions.
 * Routes are very important mechanism that allows you to freely connect
 * different URLs to chosen controllers and their actions (functions).
 *
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link          https://cakephp.org CakePHP(tm) Project
 * @license       https://opensource.org/licenses/mit-license.php MIT License
 */

use Cake\Http\Middleware\CsrfProtectionMiddleware;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;

/**
 * The default class to use for all routes
 *
 * The following route classes are supplied with CakePHP and are appropriate
 * to set as the default:
 *
 * - Route
 * - InflectedRoute
 * - DashedRoute
 *
 * If no call is made to `Router::defaultRouteClass()`, the class used is
 * `Route` (`Cake\Routing\Route\Route`)
 *
 * Note that `Route` does not do any inflections on URLs which will result in
 * inconsistently cased URLs when used with `:plugin`, `:controller` and
 * `:action` markers.
 *
 * Cache: Routes are cached to improve performance, check the RoutingMiddleware
 * constructor in your `src/Application.php` file to change this behavior.
 *
 */
Router::defaultRouteClass(DashedRoute::class);
Router::extensions(['xlsx']);
Router::scope('/', function (RouteBuilder $routes) {
    // Register scoped middleware for in scopes.
    $routes->registerMiddleware('csrf', new CsrfProtectionMiddleware([
        'httpOnly' => true
    ]));

    /**
     * Apply a middleware to the current route scope.
     * Requires middleware to be registered via `Application::routes()` with `registerMiddleware()`
     */
    $routes->applyMiddleware('csrf');

    /**
     * Here, we are connecting '/' (base path) to a controller called 'Pages',
     * its action called 'display', and we pass a param to select the view file
     * to use (in this case, src/Template/Pages/home.ctp)...
     */
    // $routes->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);
    $routes->connect('/', ['controller' => 'Orders', 'action' => 'index']);

    /**
     * ...and connect the rest of 'Pages' controller's URLs.
     */
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);


    /**
     * Connect catchall routes for all controllers.
     *
     * Using the argument `DashedRoute`, the `fallbacks` method is a shortcut for
     *
     * ```
     * $routes->connect('/:controller', ['action' => 'index'], ['routeClass' => 'DashedRoute']);
     * $routes->connect('/:controller/:action/*', [], ['routeClass' => 'DashedRoute']);
     * ```
     *
     * Any route class can be used with this method, such as:
     * - DashedRoute
     * - InflectedRoute
     * - Route
     * - Or your own route class
     *
     * You can remove these routes once you've connected the
     * routes you want in your application.
     */
    $routes->fallbacks(DashedRoute::class);
});

/**
 * If you need a different set of middleware or none at all,
 * open new scope and define routes there.
 *
 * ```
 * Router::scope('/api', function (RouteBuilder $routes) {
 *     // No $routes->applyMiddleware() here.
 *     // Connect API actions here.
 * });
 * ```
 */

Router::scope('/google', function (RouteBuilder $routes) {
    $routes->connect('/auth/', ['controller' => 'GoogleCalendar', 'action' => 'auth']);

});

Router::prefix('api', function ($routes) {
    //$routes->connect('/', ['controller' => 'Users', 'action' => 'index']);
    $routes->extensions(['json']);
    $routes->resources('Users');
    $routes->resources('Customers');
    $routes->resources('Salesmen');
    $routes->resources('Orders');
    $routes->resources('OrderItems');
    $routes->resources('Products');
    $routes->resources('Bill');
    $routes->resources('Claims');
    $routes->resources('CreditApplications');
    //ContactsList
    $routes->resources('ContactsList');
    // All routes here will be prefixed with `/admin`
    // And have the prefix => admin route element added.
    
    // Abhishek - ToolKitAPI
	$routes->resources('ToolKits');
    
    $routes->fallbacks('DashedRoute');
});


Router::prefix('sales', function ($routes) {
    // All routes here will be prefixed with `/admin`
    // And have the prefix => admin route element added.
    $routes->registerMiddleware('csrf', new CsrfProtectionMiddleware([
        'httpOnly' => true
    ]));
    $routes->applyMiddleware('csrf');
    $routes->fallbacks('DashedRoute');
});

Router::prefix('sdm', function ($routes) {
    // All routes here will be prefixed with `/sdm`
    // And have the prefix => sdm route element added.
    $routes->registerMiddleware('csrf', new CsrfProtectionMiddleware([
        'httpOnly' => true
    ]));
    $routes->applyMiddleware('csrf');
    $routes->fallbacks('DashedRoute');
});

src/Model/Table/ClaimsTable.php
<?php

namespace App\Model\Table;

use Cake\ORM\Query;
use Cake\ORM\RulesChecker;
use Cake\ORM\Table;
use Cake\Validation\Validator;

/**
 * Claims Model
 *
 * @property &\Cake\ORM\Association\BelongsTo $Customers
 * @property &\Cake\ORM\Association\BelongsTo $Consumers
 * @property \App\Model\Table\ClaimProductsTable&\Cake\ORM\Association\HasMany $ClaimStatus
 *
 * @method \App\Model\Entity\Claim get($primaryKey, $options = [])
 * @method \App\Model\Entity\Claim newEntity($data = null, array $options = [])
 * @method \App\Model\Entity\Claim[] newEntities(array $data, array $options = [])
 * @method \App\Model\Entity\Claim|false save(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Claim saveOrFail(\Cake\Datasource\EntityInterface $entity, $options = [])
 * @method \App\Model\Entity\Claim patchEntity(\Cake\Datasource\EntityInterface $entity, array $data, array $options = [])
 * @method \App\Model\Entity\Claim[] patchEntities($entities, array $data, array $options = [])
 * @method \App\Model\Entity\Claim findOrCreate($search, callable $callback = null, $options = [])
 */
class ClaimsTable extends Table
{
    /**
     * Initialize method
     *
     * @param array $config The configuration for the Table.
     * @return void
     */
    public function initialize(array $config)
    {
        parent::initialize($config);

        $this->setTable('claims');
        $this->setDisplayField('id');
        $this->setPrimaryKey('id');
        $this->belongsTo('Customers', [
            'foreignKey' => 'customer_id'
        ]);
        $this->belongsTo('Consumers', [
            'foreignKey' => 'consumer_id'
        ]);
        $this->belongsTo('Users', [
            'foreignKey' => 'created_by'
        ]);
        $this->belongsTo('Millers', [
            'foreignKey' => 'miller_id'
        ]);
        $this->belongsTo('Users', [
            'foreignKey' => 'miller_user_id'
        ]);
        $this->hasMany('ClaimStatus', [
            'foreignKey' => 'claim_id'
        ]);
    }

    /**
     * Default validation rules.
     *
     * @param \Cake\Validation\Validator $validator Validator instance.
     * @return \Cake\Validation\Validator
     */
    public function validationDefault(Validator $validator)
    {
        $validator
            ->allowEmptyString('id', null, 'create');

        /*$validator
            ->scalar('claim_number')
            ->maxLength('claim_number', 50)
            ->allowEmptyString('claim_number');

        $validator
            ->scalar('dealer_invoice')
            ->maxLength('dealer_invoice', 50)
            ->allowEmptyString('dealer_invoice');

        $validator
            ->scalar('primco_invoice')
            ->maxLength('primco_invoice', 50)
            ->allowEmptyString('primco_invoice');

        $validator
            ->scalar('type_of_claim')
            ->maxLength('type_of_claim', 50)
            ->allowEmptyString('type_of_claim');

        $validator
            ->integer('quantity_purchased')
            ->allowEmptyString('quantity_purchased');

        $validator
            ->date('notification_date')
            ->allowEmptyDate('notification_date');

        $validator
            ->scalar('photo_attached')
            ->allowEmptyString('photo_attached');

        $validator
            ->scalar('samples_available')
            ->allowEmptyString('samples_available');

        $validator
            ->scalar('detailed_claim_reason')
            ->allowEmptyString('detailed_claim_reason');

        $validator
            ->dateTime('created_date')
            ->allowEmptyDateTime('created_date');

        $validator
            ->scalar('date_installed')
            ->maxLength('date_installed', 100)
            ->allowEmptyString('date_installed');

        $validator
            ->scalar('areas_installed')
            ->maxLength('areas_installed', 100)
            ->allowEmptyString('areas_installed');

        $validator
            ->scalar('installed')
            ->maxLength('installed', 10)
            ->allowEmptyString('installed');

        $validator
            ->scalar('request_for_resolution')
            ->allowEmptyString('request_for_resolution');*/

        return $validator;
    }

    /**
     * Returns a rules checker object that will be used for validating
     * application integrity.
     *
     * @param \Cake\ORM\RulesChecker $rules The rules object to be modified.
     * @return \Cake\ORM\RulesChecker
     */
    public function buildRules(RulesChecker $rules)
    {
        $rules->add($rules->existsIn(['customer_id'], 'Customers'));

        return $rules;
    }
}

src/Controller/Api/ClaimsController.php
<?php
namespace App\Controller\Api;
use Cake\I18n\Time;
use Cake\ORM\TableRegistry;
use App\Controller\AppController;

/**
 * Claims Controller
 *
 *
 * @method \App\Model\Entity\Claim[]|\Cake\Datasource\ResultSetInterface paginate($object = null, array $settings = [])
 */
class ClaimsController extends AppController
{
    /**
     * Index method
     *
     * @return \Cake\Http\Response|null
     */
    public function index()
    {
		$bill = $this->Claim->find('all');
		echo json_encode(array("response"=>$bill));
		exit;

    }

    /**
     * View method
     *
     * @param string|null $id Bill id.
     * @return \Cake\Http\Response|null
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $bill = $this->Bill->get($id, [
            'contain' => []
        ]);

        $this->set('Bill', $bill);
    }

    /**
     * Add method
     *
     * @return \Cake\Http\Response|null Redirects on successful add, renders view otherwise.
     */
	 public function add()
    {
        $bill = $this->Bill->newEntity();
		$this->request->allowMethod(['post', 'put']);
        if ($this->request->is('post')) {

			$data = $this->request->getData();

			if (!empty($data['billing_image'])) {
				$dataimage = $data['billing_image'];
				list($type, $dataimage) = explode(';', $dataimage);
				list(, $dataimage)      = explode(',', $dataimage);
				$dataimage = base64_decode($dataimage);
				$newfilename = uniqid(). '.png';
				file_put_contents('bill_image/'.$newfilename, $dataimage);
				$data['billing_image'] = $newfilename;
			}



            $bill = $this->Bill->patchEntity($bill, $this->request->getData());
            if ($this->Bill->save($bill)) {
				echo json_encode(array("response"=>"Done"));
				exit;
			   $this->set('bill', $bill);
            }else{
				echo json_encode(array("response"=>"Error"));
				exit;
			}
        }
    }
    /* public function add()
    {
        $bill = $this->Bill->newEntity();
        if ($this->request->is('post')) {
            $bill = $this->Bill->patchEntity($Bill, $this->request->getData());
            if ($this->Bill->save($Bill)) {
                $this->Flash->success(__('The Bill has been saved.'));

                return $this->redirect(['action' => 'index']);
            }
            $this->Flash->error(__('The Bill could not be saved. Please, try again.'));
        }
        $this->set(compact('Bill'));
    } */

    /**
     * Edit method
     *
     * @param string|null $id Bill id.
     * @return \Cake\Http\Response|null Redirects on successful edit, renders view otherwise.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function edit($id = null)
    {
        $bill = $this->Bill->get($id, [
            'contain' => []
        ]);
        if ($this->request->is(['patch', 'post', 'put'])) {
			$data =  $this->request->getData();
			if (!empty($data['billing_image'])) {
				$dataimage = $data['billing_image'];
				list($type, $dataimage) = explode(';', $dataimage);
				list(, $dataimage)      = explode(',', $dataimage);
				$dataimage = base64_decode($dataimage);
				$newfilename = uniqid(). '.png';
				file_put_contents('bill_image/'.$newfilename, $dataimage);
				$data['billing_image'] = $newfilename;
			}
			if(!empty($data['billing_status'])){
			if($data['billing_status'] == 'D'){
				$data['billing_status'] = 'R';

				$articlesTable = TableRegistry::getTableLocator()->get('BillComment');
				$article = $articlesTable->newEntity();

				$article->comment = $data['billing_comment'];
				$article->billid = $id;

				if ($articlesTable->save($article)) {
					// The $article entity contains the id now
					$id = $article->id;
				}
				unset($data['billing_comment']);
			}
			}
            $bill = $this->Bill->patchEntity($bill,$data);
            if ($this->Bill->save($bill)) {
                echo json_encode(array("response"=>"Done"));
				exit;
            }
            //$this->Flash->error(__('The Bill could not be saved. Please, try again.'));
        }
        //$this->set(compact('Bill'));
    }

    /**
     * Delete method
     *
     * @param string|null $id Bill id.
     * @return \Cake\Http\Response|null Redirects to index.
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function delete($id = null)
    {
        $this->request->allowMethod(['post', 'delete']);
        $bill = $this->Bill->get($id);
        if ($this->Bill->delete($bill)) {

			echo json_encode(array("response"=>"Done"));
				exit;
           // $this->Flash->success(__('The Bill has been deleted.'));
        } else {
           // $this->Flash->error(__('The Bill could not be deleted. Please, try again.'));
        }

        //return $this->redirect(['action' => 'index']);
    }
}

src/Controller/Sales/PagesController.php
<?php
/**
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link      https://cakephp.org CakePHP(tm) Project
 * @since     0.2.9
 * @license   https://opensource.org/licenses/mit-license.php MIT License
 */
namespace App\Controller;

use Cake\Core\Configure;
use Cake\Http\Exception\ForbiddenException;
use Cake\Http\Exception\NotFoundException;
use Cake\View\Exception\MissingTemplateException;

/**
 * Static content controller
 *
 * This controller will render views from Template/Pages/
 *
 * @link https://book.cakephp.org/3.0/en/controllers/pages-controller.html
 */
class PagesController extends AppController
{

    /**
     * Displays a view
     *
     * @param array ...$path Path segments.
     * @return \Cake\Http\Response|null
     * @throws \Cake\Http\Exception\ForbiddenException When a directory traversal attempt.
     * @throws \Cake\Http\Exception\NotFoundException When the view file could not
     *   be found or \Cake\View\Exception\MissingTemplateException in debug mode.
     */
    public function display(...$path)
    {
        $count = count($path);
        if (!$count) {
            return $this->redirect('/');
        }
        if (in_array('..', $path, true) || in_array('.', $path, true)) {
            throw new ForbiddenException();
        }
        $page = $subpage = null;

        if (!empty($path[0])) {
            $page = $path[0];
        }
        if (!empty($path[1])) {
            $subpage = $path[1];
        }
        $this->set(compact('page', 'subpage'));

        try {
            $this->render(implode('/', $path));
        } catch (MissingTemplateException $exception) {
            if (Configure::read('debug')) {
                throw $exception;
            }
            throw new NotFoundException();
        }
    }
}

src/Template/Sales/Claims/index.ctp
<?php
/**
 * @var \App\View\AppView $this
 * @var \App\Model\Entity\Claim[]|\Cake\Collection\CollectionInterface $claims
 */
?>
<!--nav class="large-3 medium-4 columns" id="actions-sidebar">
    <ul class="side-nav">
        <li class="heading"><?= __('Actions') ?></li>
        <li><?= $this->Html->link(__('New Claim'), ['action' => 'add']) ?></li>
        <li><?= $this->Html->link(__('List Customers'), ['controller' => 'Customers', 'action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('New Customer'), ['controller' => 'Customers', 'action' => 'add']) ?></li>
        <li><?= $this->Html->link(__('List Consumers'), ['controller' => 'Consumers', 'action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('New Consumer'), ['controller' => 'Consumers', 'action' => 'add']) ?></li>
        <li><?= $this->Html->link(__('List Claim Products'), ['controller' => 'ClaimProducts', 'action' => 'index']) ?></li>
        <li><?= $this->Html->link(__('New Claim Product'), ['controller' => 'ClaimProducts', 'action' => 'add']) ?></li>
    </ul>
</nav  -->
<style>
    .message.success {
        margin-top: 1rem;
        background: #0d4219;
        text-align: center;
        color: #fff;
        -webkit-transition: -webkit-box-shadow .25s;
        -moz-transition: box-shadow .25s;
        -o-transition: box-shadow .25s;
        transition: -webkit-box-shadow .25s;
        transition: box-shadow .25s;
        transition: box-shadow .25s, -webkit-box-shadow .25s;
        border-radius: 2px;
    }
</style>
<div class="orders index large-9 medium-8 columns content card card card-default scrollspy">
    <div class="card-content">
        <div class="claims index large-9 medium-8 columns content">

            <table cellpadding="0" cellspacing="0">
                <thead>
                    <tr>
                        <th scope="col"><?= $this->Paginator->sort('id') ?></th>
                        <th scope="col"><?= $this->Paginator->sort('customer_name') ?></th>
                        <th scope="col"><?= $this->Paginator->sort('retailer_name') ?></th>
                        <th scope="col"><?= $this->Paginator->sort('total_claim_products') ?></th>
                        <th scope="col"><?= $this->Paginator->sort('status') ?></th>
                        <th scope="col"><?= $this->Paginator->sort('created_date') ?></th -->
                        <th scope="col" class="actions"><?= __('Actions') ?></th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($claims as $claim): ?>
                    <tr>
                        <td><?= $this->Number->format($claim->id) ?></td>
                        <td><?= h($claim->customer->name) ?></td>
                        <td><?php echo !empty($claim->retailer) ? ($claim->retailer->retailer_name) : '' ?></td>
                        <td><?= is_array($claim->claim_json) ? h(count($claim->claim_json)) : 0 ?></td>
                        <?php
                        $claimStatuses = $claim->claim_status;
                        $totalStatuses = count($claimStatuses);
                        $status = 'Pending';
                        if($totalStatuses > 0) {
                            $status = $claimStatuses[$totalStatuses - 1]['status'];
                        }
                        ?>
                        <td><?= h(ucfirst($status)) ?></td>
                        <td><?= h($claim->created_date) ?></td>
                        <td class="actions">
                            <?= $this->Html->link(__('View'), ['action' => 'view', $claim->id]) ?>
                            <?= $this->Form->postLink(__('Delete'), ['action' => 'delete', $claim->id], ['confirm' => __('Are you sure you want to delete # {0}?', $claim->id)]) ?>
                        </td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
            <div class="paginator">
                <ul class="pagination">
                    <?= $this->Paginator->first('<< ' . __('first')) ?>
                    <?= $this->Paginator->prev('< ' . __('previous')) ?>
                    <?= $this->Paginator->numbers() ?>
                    <?= $this->Paginator->next(__('next') . ' >') ?>
                    <?= $this->Paginator->last(__('last') . ' >>') ?>
                </ul>
                <p><?= $this->Paginator->counter(['format' => __('Page {{page}} of {{pages}}, showing {{current}} record(s) out of {{count}} total')]) ?></p>
            </div>
        </div>
    </div>
</div>

src/Template/Sales/Claims/thankyou.ctp
<?php

?> 
    <div class="row">
                <div class="col-12 m-0 p-0">
                    <div class="text-center"> 
                      <div class="logo-container p-4">
					 
					   <?= $this->Html->image('logo.png'); ?> 
					</div>		
					<h2 class="m-4">Thank you so much for Credit Application with Primco</h2> 					
              <p>
      					  <?php echo $this->Html->link(
      						'Back to Home',
      						['controller' => 'Users', 'action' => 'login'],
      						['class' => 'btn btn-primary']
      					); ?>

                <?php  echo $this->Html->link(
                  'Edit Claim Form',
                  ['controller' => 'Claims', 'action' => 'editclaim',base64_encode($claim->id )],
                  ['class' => 'btn btn-warning']
                );  
                 ?>
      					
      					
      					<?php 
                if($link){
                    echo $this->Html->link(
                      'Preview and Download',
                      $link,
                      ['class' => 'btn btn-info']
                    ); 
                }
                
                ?>
                        
              </p>
                      <div>
                        <?php if($image_name): ?>
                          
                           <?= $this->Html->image('/img/QRcode/'.$image_name ) ?> 
                        <?php endif; ?>
                      </div>
                      
                    </div>
            </div>
    </div>